timer(); 

[fmin, xmin, out] = cmaes( ...
    felli, ...
    x0 = 1 * ones(10,1), ...
    sigma = 1,...
    logmod = 10, ...
    savemod = 200, ...
    plotmod = 200, ...
    mu=[], ...
    lambda=[], ...
    stopfitness = 1e-9, ... 
    stopfunevals = 9e9);

disp(timer())
